### ISSUE TITLE
Feature request: `Form:set_as_inventory_for(player)`

### ISSUE THREAD

**Issue by Lazerbeak12345** [luk3yx/minetest-flow#1]
I'd like to prefix this feature request with a statement that not only am I willing to make this PR for you, I actually already know how I'd do it. Just let me know.

---

## The problem

There's one feature that flow can't do right now, and that is the "player formspec," as mentioned by this api:

> * `set_inventory_formspec(formspec)`
>     * Redefine player's inventory form
>     * Should usually be called in `on_joinplayer`
>     * If `formspec` is `""`, the player's inventory is disabled.

## Alternative

I've actually experimented with this and found that if I wanted to _force_ flow to do this, it would work like this:

- Manually call `_render` (in the same way as your unit tests), using code from `show_form`
- Manually manage state, and more or less copy a cloned version of `on_fs_input`.

This second bullet point in here is not something I'd like to do - especially since if (or when) you update how `on_fs_input` works, that update will not cascade downstream to these copied functions.

## My proposal

- Split the private `show_form` into two functions
  - local function `prepare_form`, which does _everything_ that `show_form` does, but instead of calling `minetest.show_formspec`, it returns the formspec string.
  - `show_form`, which calls `prepare_form`, then calls `minetest.show_formspec` on the result.
- Add a new function `Form:set_as_inventory_for()`. I'm not confidant in the name, but the functionality is more important. It calls `prepare_form` and passes the result into `player:set_inventory_formspec()`. ~~An update function would not be needed, and the `Form:update` * functions would do nothing.~~ _This is incorrect. See below for solution_

Example of use:

```lua
local stupid_simple_inv = flow.make_gui(function (p, c)
	return gui.List{
		inventory_location = "current_player",
		list_name = "main",
		w = 8,
		h = 4,
	}
end)
minetest.register_on_joinplayer(function(player)
	stupid_simple_inv:set_as_inventory_for(player)
end)
```

### Problem 1 with this proposal

A new special case will have to be added for `update_form`. We don't want it to call `show_form` for an inventory formspec.

#### Potential solution for for problem 1

- Add a flag to the context that is checked for in `update_form` that will tell it to _not_ call update form, and instead re-set the inventory formspec. We may want to abstract the `Form:set_as_inventory_for(player)` function for this to work.

This would actually mean that the `update` * functions would work as well.

### Problem 2 with this proposal

Players can only have one open formspec at a time. This would occupy that slot.

#### Potential solution for problem 2

Inventory Formspecs are always named `""`. This special case can be checked for and a different form info variable used in the multiple locations involved. An abstraction like that used in sfinv to set or unset form info (in sfinv's case it was ctx only) would be wise.

**Comment by Lazerbeak12345** [comment]
Problem 2 solved. Ofc while I wait on your reply I'll keep brainstorming.

**Comment by luk3yx** [comment]
Hi, thanks for your feature request and offer to create a PR. I think that using a separate state table for inventory formspecs (like you've mentioned) is the best way to work around both problems.

Would it be better for flow to register sfinv pages instead so that inventory GUIs made with flow can work with other mods that use sfinv?

```lua
local my_gui = flow.make_gui(...)

my_gui:register_sfinv_page("mymod:sfinv_page", {
    title = "New tab",
    override = false  -- Set to true to override an existing page (like sfinv:crafting)
})
```

**Comment by Lazerbeak12345** [comment]
Wouldn't be a bad idea, but I think it's too specific. We don't want to have to add support for every single inventory mod, especially ones outside of the MTG ecosystem. As it is this is very generic. Good idea for future mods perhaps. Not sure.

A more general approach where there's an API that provides a formspec string and a function to be called upon an fs submission might also work well, if that interests you.

---

I'll be transparent and admit that also I've started work on a highly experimental inventory mod using flow, which is my motivation for this.

**Comment by luk3yx** [comment]
> A more general approach where there's an API that provides a formspec string and a function to be called upon an fs submission might also work well, if that interests you.

I think that would be good. If the `set_as_inventory_for` function is much simpler to implement then I'd be okay with it, I just don't think it would be as useful.

> I'll be transparent and admit that also I've started work on a highly experimental inventory mod using flow, which is my motivation for this.

Ah, I see why relying on sfinv won't help. I've had a quick look at your mod and noticed a couple of things:

 - Most mods that use sfinv use the [old coordinate system](https://minetest.gitlab.io/minetest/formspec/#migrating-to-real-coordinates), it would be difficult to keep compatibility with sfinv's API. While you can switch to/from real_coordinates (the new system) in the middle of a formspec, it would be very difficult to do so with flow since `container[]` offsets are different depending on whether real_coordinates is enabled for each element.
 - I don't think I've tested tabheader, it may not be positioned/layouted correctly.
 - `gui.embed` is deprecated because it's slow (as it parses the formspec) and hasn't been used by anything until now. It should be safe to just copy the function to your own mod if you need it, so long as formspecs passed to it only use real coordinates.

**Comment by Lazerbeak12345** [comment]
> > A more general approach where there's an API that provides a formspec string and a function to be called upon an fs submission might also work well, if that interests you.
> 
> I think that would be good. If the `set_as_inventory_for` function is much simpler to implement then I'd be okay with it, I just don't think it would be as useful.

I'm still open to draft a PR for this too. It doesn't have to be mutually exclusive.

**Comment by Lazerbeak12345** [comment]
> I've had a quick look at your mod and noticed a couple of things

Thanks. I'll keep that all in mind.
